# Default values for package service.
nameOverride: package
replicaCount: 1
dockerregistrynamespace:
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
reason: unknown
readinessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 40
  periodSeconds: 15
  timeoutSeconds: 2
  failureThreshold: 5
livenessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 50
  periodSeconds: 15
log:
  level: error
cosmosDb:
  collectionName:
tags:
  dev: false
  prod: false
  qa: false
  staging: false
current: false
autoscaling:
  enabled: false
  maxReplicas:
  minReplicas:
  targetCPUUtilizationPercentage:
networkPolicy:
  egress:
    enabled: true
    # allowAll will be ingnored if customSelectons are provided. Comment out
    # customSelectors if allowAll is required
    allowAll: false
    customSelectors:
      # allow egress traffic to kubedns
      - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
        ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
  ingress:
    enabled: true
    # allowAll will be ingnored if customSelectons are provided. Comment out
    # customSelectors if allowAll is required
    allowAll: false
    customSelectors:
      # allow ingress traffic from workflow
      templateSelector:
        - podSelector:
            matchLabels:
              dd.fabrikam.com/egress-package: true
              app.kubernetes.io/component: backend
              app.kubernetes.io/part-of: dronedelivery
service:
  targetPort: 80
  targetProtocol: TCP
