version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Fabrikam.DroneDelivery.sln && dotnet test Fabrikam.DroneDelivery.DeliveryService.Tests/Fabrikam.DroneDelivery.DeliveryService.Tests.csproj && dotnet publish ./Fabrikam.DroneDelivery.sln -c Release -o ./obj/Docker/publish"
