version: '3'

services:
  delivery:
    image: fabrikam.dronedelivery.deliveryservice
    build:
      context: ./Fabrikam.DroneDelivery.DeliveryService
      dockerfile: Dockerfile

  dronescheduler:
    image: mockdronescheduler
    build:
      context: ./MockDroneScheduler
      dockerfile: Dockerfile

  deliveryscheduler:
    image: mockdeliveryscheduler
    build:
      context: ./MockDeliveryScheduler
      dockerfile: Dockerfile

  account:
    image: mockaccountservice
    build:
      context: ./MockAccountService
      dockerfile: Dockerfile

  thirdparty:
    image: mockthirdpartyservice
    build:
      context: ./MockThirdPartyService
      dockerfile: Dockerfile
