##  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# Delivery allow egress traffic
###################################################################################################

{{- if .Values.networkPolicy.egress.enabled }}
{{- $fullname := include "delivery.fullname" . | replace "." "" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname  }}-np-whitelist-egress-traffic
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "delivery.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: dronedelivery
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  policyTypes:
  - Egress
{{- if .Values.networkPolicy.egress.customSelectors }}
  egress:
{{ toYaml .Values.networkPolicy.egress.customSelectors | indent 2 }}
{{- else if .Values.networkPolicy.egress.allowAll }}
  egress: []
{{- end -}}
{{ end }}
