# Default values for ingestion.
replicaCount: 1
dockerregistrynamespace:
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
reason: unknown
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 80
  initialDelaySeconds: 120
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: /api/probe
    port: 80
  initialDelaySeconds: 120
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 5
telemetry:
  level: "error"
tags:
  dev: false
  prod: false
  qa: false
  staging: false
current: false
autoscaling:
  enabled: false
  maxReplicas:
  minReplicas:
  targetCPUUtilizationPercentage:
networkPolicy:
  egress:
    enabled: true
    # allowAll will be ingnored if customSelectons are provided. Comment out
    # customSelectors if allowAll is required
    allowAll: false
    customSelectors:
      # allow egress traffic to kubedns
      - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
        ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
  ingress:
    enabled: true
    # allowAll will be ingnored if customSelectons are provided. Comment out
    # customSelectors if allowAll is required
    allowAll: false
    # customSelectors:
    #  templateSelector:
    #  argSelector:
service:
  targetPort: 80
  targetProtocol: TCP
